bots:
  - botId: 点点
    enabled: true
    mode: hybrid
    ws:
      url: ws://192.168.2.14:13001/
      accessToken: lxy666666.@
      heartbeatIntervalMs: 30000
      reconnectIntervalMs: 5000
    http:
      baseUrl: http://192.168.2.14:13000/
      accessToken: IBC39ocS1ceznq87
      timeoutMs: 5000
  - botId: ikun
    enabled: true
    mode: hybrid
    ws:
      url: ws://192.168.2.14:7301/
      accessToken: 2fJUQRsGV8MRLpzWOGShEMe5CC5o9Gj9JiNRMtBDPys
      heartbeatIntervalMs: 30000
      reconnectIntervalMs: 5000
    http:
      baseUrl: http://192.168.2.14:7300/
      accessToken: vfHQhLw6Spy8AAVZ-VPu9kPW42a7Kzu6hVjIR5WrDEI
      timeoutMs: 5000
